<script setup>
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import Modal from '@/Components/Modal.vue';
import TextInput from '@/Components/TextInput.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
import { ArchiveRestore, CalendarClock, Pencil, PiggyBank, Plus, Trash2, X } from '@lucide/vue';
import { onMounted, ref } from 'vue';

const props = defineProps({ pockets: Array, accounts: Array, deletedPockets: Array });
const createModalOpen = ref(false);
const editingPocket = ref(null);
const deletingPocket = ref(null);
const restoringPocketId = ref(null);
const newOperationId = () => crypto.randomUUID();
const createForm = useForm({ account_id: '', name: '', operation_id: newOperationId() });
const editForm = useForm({ name: '' });
const deleteForm = useForm({});
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const formatMoney = (value) => money.format(Number(value));
const formatDate = (value) => new Intl.DateTimeFormat('pt-BR').format(new Date(value));
const openCreateModal = () => { createForm.clearErrors(); createModalOpen.value = true; };
const closeCreateModal = () => { if (createForm.processing) return; createModalOpen.value = false; createForm.reset(); createForm.operation_id = newOperationId(); };
const submitCreate = () => createForm.post(route('pockets.store'), { preserveScroll: true, onSuccess: closeCreateModal });
const openEditModal = (pocket) => { editingPocket.value = pocket; editForm.name = pocket.name; editForm.clearErrors(); };
const closeEditModal = () => { if (editForm.processing) return; editingPocket.value = null; editForm.reset(); };
const submitEdit = () => editForm.patch(route('pockets.update', editingPocket.value.id), { preserveScroll: true, onSuccess: closeEditModal });
const submitDelete = () => deleteForm.delete(route('pockets.destroy', deletingPocket.value.id), { preserveScroll: true, onSuccess: () => { deletingPocket.value = null; } });
const closeDeleteModal = () => { if (!deleteForm.processing) deletingPocket.value = null; };
const restore = (pocket) => { restoringPocketId.value = pocket.id; router.post(route('pockets.restore', pocket.id), {}, { preserveScroll: true, onFinish: () => { restoringPocketId.value = null; } }); };
onMounted(() => { if (props.accounts.length && new URLSearchParams(window.location.search).has('create')) openCreateModal(); });
</script>

<template>
    <Head title="Caixinhas" />
    <AuthenticatedLayout>
        <section class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-violet-700">Objetivos e reservas</p><h1 class="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Caixinhas</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Separe valores para objetivos específicos sem perder a conta à qual pertencem.</p></div><button v-if="accounts.length" type="button" class="flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800" @click="openCreateModal"><Plus :size="18" />Criar caixinha</button></section>
        <section v-if="pockets.length" class="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="pocket in pockets" :key="pocket.id" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-50 text-violet-700"><PiggyBank :size="23" /></span><div class="flex gap-1"><button type="button" class="rounded-lg p-2 text-slate-400 hover:bg-slate-100" :aria-label="`Renomear ${pocket.name}`" @click="openEditModal(pocket)"><Pencil :size="17" /></button><button type="button" class="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-700" :aria-label="`Excluir ${pocket.name}`" @click="deletingPocket = pocket"><Trash2 :size="17" /></button></div></div><p class="mt-6 text-sm font-medium text-slate-500">{{ pocket.name }}</p><p class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{{ formatMoney(pocket.balance) }}</p><p class="mt-4 text-xs text-slate-400">Vinculada a {{ pocket.account.name }}</p></article></section>
        <div v-else class="mt-8 flex min-h-[28rem] flex-col items-center justify-center rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center shadow-sm"><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-50 text-violet-700"><PiggyBank :size="29" /></span><h2 class="mt-6 text-xl font-semibold text-slate-950">{{ accounts.length ? 'Nenhuma caixinha criada' : 'Crie uma conta primeiro' }}</h2><p class="mt-2 max-w-md text-sm leading-6 text-slate-500">{{ accounts.length ? 'Crie uma reserva inicialmente zerada dentro de uma conta.' : 'Toda caixinha precisa pertencer a uma conta ativa.' }}</p><button v-if="accounts.length" type="button" class="mt-6 flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" @click="openCreateModal"><Plus :size="18" />Criar caixinha</button></div>
        <section v-if="deletedPockets.length" class="mt-10"><div class="flex items-center gap-2"><ArchiveRestore :size="19" class="text-slate-500" /><h2 class="font-semibold text-slate-900">Excluídas recentemente</h2></div><div class="mt-4 grid gap-3"><article v-for="pocket in deletedPockets" :key="pocket.id" class="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-center"><div><p class="text-sm font-semibold text-slate-800">{{ pocket.name }}</p><p class="mt-1 text-xs text-slate-500">{{ pocket.account_name }}</p><p class="mt-1 flex items-center gap-1.5 text-xs text-slate-500"><CalendarClock :size="14" />Disponível até {{ formatDate(pocket.restorable_until) }}</p></div><button type="button" class="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 disabled:opacity-50" :disabled="restoringPocketId !== null" @click="restore(pocket)"><ArchiveRestore :size="16" />{{ restoringPocketId === pocket.id ? 'Restaurando...' : 'Restaurar' }}</button></article></div></section>
        <Modal :show="createModalOpen" max-width="lg" @close="closeCreateModal"><form class="p-6 sm:p-7" @submit.prevent="submitCreate"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-violet-700">Nova caixinha</p><h2 class="mt-1 text-xl font-semibold text-slate-950">Qual é seu objetivo?</h2></div><button type="button" class="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Fechar" @click="closeCreateModal"><X :size="20" /></button></div><div class="mt-6 grid gap-5"><div><InputLabel for="pocket-account" value="Conta" /><select id="pocket-account" v-model="createForm.account_id" class="mt-2 block w-full rounded-md border-slate-300 shadow-sm focus:border-violet-500 focus:ring-violet-500"><option value="" disabled>Selecione uma conta</option><option v-for="account in accounts" :key="account.id" :value="account.id">{{ account.name }} · {{ formatMoney(account.available_balance) }} disponível</option></select><InputError class="mt-2" :message="createForm.errors.account_id" /></div><div><InputLabel for="pocket-name" value="Nome da caixinha" /><TextInput id="pocket-name" v-model="createForm.name" class="mt-2 block w-full" autofocus /><InputError class="mt-2" :message="createForm.errors.name" /></div><p class="rounded-2xl bg-violet-50 p-4 text-sm leading-6 text-violet-800">A caixinha começa zerada. Criá-la não altera o saldo; o dinheiro entrará depois por transferência.</p></div><div class="mt-7 flex justify-end gap-3"><button type="button" class="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600" @click="closeCreateModal">Cancelar</button><button type="submit" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" :disabled="createForm.processing">{{ createForm.processing ? 'Criando...' : 'Criar caixinha' }}</button></div></form></Modal>
        <Modal :show="editingPocket !== null" max-width="md" @close="closeEditModal"><form class="p-6" @submit.prevent="submitEdit"><div class="flex items-center justify-between gap-4"><h2 class="text-xl font-semibold text-slate-950">Renomear caixinha</h2><button type="button" class="rounded-lg p-2 text-slate-400" aria-label="Fechar" @click="closeEditModal"><X :size="20" /></button></div><div class="mt-6"><InputLabel for="edit-pocket-name" value="Nome da caixinha" /><TextInput id="edit-pocket-name" v-model="editForm.name" class="mt-2 block w-full" /><InputError class="mt-2" :message="editForm.errors.name" /></div><div class="mt-7 flex justify-end gap-3"><button type="button" class="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600" @click="closeEditModal">Cancelar</button><button type="submit" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" :disabled="editForm.processing">Salvar</button></div></form></Modal>
        <Modal :show="deletingPocket !== null" max-width="md" labelled-by="delete-pocket-title" :closeable="!deleteForm.processing" @close="closeDeleteModal"><div class="p-6"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-rose-50 text-rose-700"><Trash2 :size="22" /></span><h2 id="delete-pocket-title" class="mt-5 text-xl font-semibold text-slate-950">Excluir {{ deletingPocket?.name }}?</h2><p class="mt-2 text-sm leading-6 text-slate-500">Os lançamentos ativos da caixinha também serão excluídos, alterando o saldo exibido. O conjunto poderá ser restaurado por 30 dias.</p><div class="mt-7 flex justify-end gap-3"><button type="button" class="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 disabled:opacity-50" :disabled="deleteForm.processing" @click="closeDeleteModal">Cancelar</button><button type="button" class="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" :disabled="deleteForm.processing" @click="submitDelete">{{ deleteForm.processing ? 'Excluindo...' : 'Excluir caixinha' }}</button></div></div></Modal>
    </AuthenticatedLayout>
</template>
